# Generated by Django 4.1.7 on 2023-03-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
